// Code generated by "stringer -type=UnionTypes"; DO NOT EDIT.

package reflect

import "fmt"

const _UnionTypes_name = "UnionOfResourcesUnionOfTablesUnionOfExternalResources"

var _UnionTypes_index = [...]uint8{0, 16, 29, 53}

func (i UnionTypes) String() string {
	if i >= UnionTypes(len(_UnionTypes_index)-1) {
		return fmt.Sprintf("UnionTypes(%d)", i)
	}
	return _UnionTypes_name[_UnionTypes_index[i]:_UnionTypes_index[i+1]]
}
