// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import reflect "github.com/omniql/reflect"

// ApplicationContainer is an autogenerated mock type for the ApplicationContainer type
type ApplicationContainer struct {
	mock.Mock
}

// LookupImports provides a mock function with given fields:
func (_m *ApplicationContainer) LookupImports() reflect.LookupImports {
	ret := _m.Called()

	var r0 reflect.LookupImports
	if rf, ok := ret.Get(0).(func() reflect.LookupImports); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.LookupImports)
		}
	}

	return r0
}

// LookupResources provides a mock function with given fields:
func (_m *ApplicationContainer) LookupResources() reflect.LookupResources {
	ret := _m.Called()

	var r0 reflect.LookupResources
	if rf, ok := ret.Get(0).(func() reflect.LookupResources); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.LookupResources)
		}
	}

	return r0
}

// Path provides a mock function with given fields:
func (_m *ApplicationContainer) Path() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Version provides a mock function with given fields:
func (_m *ApplicationContainer) Version() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
