// Code generated by mockery v1.0.0
package mocks

import hybrids "github.com/nebtex/hybrids/golang/hybrids"
import mock "github.com/stretchr/testify/mock"
import reflect "github.com/omniql/reflect"

// FieldContainer is an autogenerated mock type for the FieldContainer type
type FieldContainer struct {
	mock.Mock
}

// Application provides a mock function with given fields:
func (_m *FieldContainer) Application() reflect.ApplicationContainer {
	ret := _m.Called()

	var r0 reflect.ApplicationContainer
	if rf, ok := ret.Get(0).(func() reflect.ApplicationContainer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.ApplicationContainer)
		}
	}

	return r0
}

// HybridType provides a mock function with given fields:
func (_m *FieldContainer) HybridType() hybrids.Types {
	ret := _m.Called()

	var r0 hybrids.Types
	if rf, ok := ret.Get(0).(func() hybrids.Types); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(hybrids.Types)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *FieldContainer) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Items provides a mock function with given fields:
func (_m *FieldContainer) Items() reflect.ItemsContainer {
	ret := _m.Called()

	var r0 reflect.ItemsContainer
	if rf, ok := ret.Get(0).(func() reflect.ItemsContainer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.ItemsContainer)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *FieldContainer) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Parent provides a mock function with given fields:
func (_m *FieldContainer) Parent() reflect.OType {
	ret := _m.Called()

	var r0 reflect.OType
	if rf, ok := ret.Get(0).(func() reflect.OType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.OType)
		}
	}

	return r0
}

// Position provides a mock function with given fields:
func (_m *FieldContainer) Position() hybrids.FieldNumber {
	ret := _m.Called()

	var r0 hybrids.FieldNumber
	if rf, ok := ret.Get(0).(func() hybrids.FieldNumber); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(hybrids.FieldNumber)
	}

	return r0
}

// ValueType provides a mock function with given fields:
func (_m *FieldContainer) ValueType() reflect.OType {
	ret := _m.Called()

	var r0 reflect.OType
	if rf, ok := ret.Get(0).(func() reflect.OType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.OType)
		}
	}

	return r0
}
