// Code generated by mockery v1.0.0
package mocks

import hybrids "github.com/nebtex/hybrids/golang/hybrids"
import mock "github.com/stretchr/testify/mock"
import reflect "github.com/omniql/reflect"

// ItemsContainer is an autogenerated mock type for the ItemsContainer type
type ItemsContainer struct {
	mock.Mock
}

// HybridType provides a mock function with given fields:
func (_m *ItemsContainer) HybridType() hybrids.Types {
	ret := _m.Called()

	var r0 hybrids.Types
	if rf, ok := ret.Get(0).(func() hybrids.Types); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(hybrids.Types)
	}

	return r0
}

// ValueType provides a mock function with given fields:
func (_m *ItemsContainer) ValueType() reflect.OType {
	ret := _m.Called()

	var r0 reflect.OType
	if rf, ok := ret.Get(0).(func() reflect.OType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.OType)
		}
	}

	return r0
}
