// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import reflect "github.com/omniql/reflect"

// TableContainer is an autogenerated mock type for the TableContainer type
type TableContainer struct {
	mock.Mock
}

// Application provides a mock function with given fields:
func (_m *TableContainer) Application() reflect.ApplicationContainer {
	ret := _m.Called()

	var r0 reflect.ApplicationContainer
	if rf, ok := ret.Get(0).(func() reflect.ApplicationContainer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.ApplicationContainer)
		}
	}

	return r0
}

// FieldCount provides a mock function with given fields:
func (_m *TableContainer) FieldCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *TableContainer) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LookupFields provides a mock function with given fields:
func (_m *TableContainer) LookupFields() reflect.LookupFields {
	ret := _m.Called()

	var r0 reflect.LookupFields
	if rf, ok := ret.Get(0).(func() reflect.LookupFields); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.LookupFields)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *TableContainer) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
