// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import reflect "github.com/omniql/reflect"

// UnionContainer is an autogenerated mock type for the UnionContainer type
type UnionContainer struct {
	mock.Mock
}

// Application provides a mock function with given fields:
func (_m *UnionContainer) Application() reflect.ApplicationContainer {
	ret := _m.Called()

	var r0 reflect.ApplicationContainer
	if rf, ok := ret.Get(0).(func() reflect.ApplicationContainer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.ApplicationContainer)
		}
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *UnionContainer) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LookupTable provides a mock function with given fields:
func (_m *UnionContainer) LookupTable() reflect.LookupTableOnUnion {
	ret := _m.Called()

	var r0 reflect.LookupTableOnUnion
	if rf, ok := ret.Get(0).(func() reflect.LookupTableOnUnion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.LookupTableOnUnion)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *UnionContainer) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
